// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-Db4bMKlZPe8ympdamNTHw3U7cuMaac',
    appId: '1:1400511824:web:e9330e4b7131f4cd63a055',
    messagingSenderId: '1400511824',
    projectId: 'chatapp-efd24',
    authDomain: 'chatapp-efd24.firebaseapp.com',
    databaseURL: 'https://chatapp-efd24-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-efd24.appspot.com',
    measurementId: 'G-L19HD3T2EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5F2nWB6GXXvLx_VHO9-_XawZoUJgc-I',
    appId: '1:1400511824:android:ea81a76b8709325463a055',
    messagingSenderId: '1400511824',
    databaseURL: 'https://chatapp-efd24-default-rtdb.firebaseio.com',
    projectId: 'chatapp-efd24',
    storageBucket: 'chatapp-efd24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFfpC8En2Jx4eShHFwBRMTJN3cWZYDXg',
    appId: '1:1400511824:ios:ee443600a3d1684f63a055',
    messagingSenderId: '1400511824',
    databaseURL: 'https://chatapp-efd24-default-rtdb.firebaseio.com',
    projectId: 'chatapp-efd24',
    storageBucket: 'chatapp-efd24.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFfpC8En2Jx4eShHFwBRMTJN3cWZYDXg',
    appId: '1:1400511824:ios:cfea940e18d9fd3463a055',
    messagingSenderId: '1400511824',
    databaseURL: 'https://chatapp-efd24-default-rtdb.firebaseio.com',
    projectId: 'chatapp-efd24',
    storageBucket: 'chatapp-efd24.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
